package banco;
// Generated 11-mar-2018 16:11:26 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer idHistorial;
     private String tipoEvento;
     private String fechaHora;
     private String numeroCuenta;

    public Historial() {
    }

    public Historial(String tipoEvento, String fechaHora, String numeroCuenta) {
       this.tipoEvento = tipoEvento;
       this.fechaHora = fechaHora;
       this.numeroCuenta = numeroCuenta;
    }
   
    public Integer getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(Integer idHistorial) {
        this.idHistorial = idHistorial;
    }
    public String getTipoEvento() {
        return this.tipoEvento;
    }
    
    public void setTipoEvento(String tipoEvento) {
        this.tipoEvento = tipoEvento;
    }
    public String getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(String fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }




}


