package banco;
// Generated 11-mar-2018 16:11:26 by Hibernate Tools 4.3.1



/**
 * Operaciones generated by hbm2java
 */
public class Operaciones  implements java.io.Serializable {


     private Integer idOperacion;
     private String fechaHora;
     private String numCuenta;
     private String tipoOperacion;
     private int cantidad;

    public Operaciones() {
    }

    public Operaciones(String fechaHora, String numCuenta, String tipoOperacion, int cantidad) {
       this.fechaHora = fechaHora;
       this.numCuenta = numCuenta;
       this.tipoOperacion = tipoOperacion;
       this.cantidad = cantidad;
    }

    public Operaciones(Integer idOperacion, String fechaHora, String numCuenta, String tipoOperacion, int cantidad) {
        this.idOperacion = idOperacion;
        this.fechaHora = fechaHora;
        this.numCuenta = numCuenta;
        this.tipoOperacion = tipoOperacion;
        this.cantidad = cantidad;
    }

  
    
   
    public Integer getIdOperacion() {
        return this.idOperacion;
    }
    
    public void setIdOperacion(Integer idOperacion) {
        this.idOperacion = idOperacion;
    }
    public String getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(String fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(String numCuenta) {
        this.numCuenta = numCuenta;
    }
    public String getTipoOperacion() {
        return this.tipoOperacion;
    }
    
    public void setTipoOperacion(String tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


