package banco;
// Generated 11-mar-2018 16:11:26 by Hibernate Tools 4.3.1

import java.util.regex.Matcher;
import java.util.regex.Pattern;




/**
 * Propietarios generated by hbm2java
 */
public class Propietarios  implements java.io.Serializable {


     private Integer idPropietario;
     private String dni;
     private String usuario;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private String numeroSecreto;

    public Propietarios() {
    }

    public Propietarios(String dni, String usuario, String nombre, String primerApellido, String segundoApellido, String numeroSecreto) {
       this.dni = dni;
       this.usuario = usuario;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.numeroSecreto = numeroSecreto;
    }
   
    public Integer getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(Integer idPropietario) {
        this.idPropietario = idPropietario;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getNumeroSecreto() {
        return this.numeroSecreto;
    }
    
    public void setNumeroSecreto(String numeroSecreto) {
        this.numeroSecreto = numeroSecreto;
    }


    
    
    
    
    public int comprobarNumSecreto(String numSecreto){
        
        int cont=0;
       
        Pattern p = Pattern.compile("[0-9]{4}");
        Matcher m = p.matcher(numSecreto);
        boolean b = m.matches();
                
        if(!b){
          cont++;
          System.err.println("El número secreto es incorrecto");
              }
        
        return cont;   
    }
    
    public int comprobarUsuario(String nombre){
        
        int cont=0;
       
        Pattern p = Pattern.compile("[A-Za-z0-9]{3,15}");
        Matcher m = p.matcher(nombre);
        boolean b = m.matches();
                
        if(!b){
          cont++;
          System.err.println("El nombre de usuario es incorrecto");
              }
        
        return cont;   
    }
    
    
    
        public int comprobarNombreApellidos(String nombre){
    
           
         int cont=0;
       
        Pattern p = Pattern.compile("[A-Za-z]{3,15}");
        Matcher m = p.matcher(nombre);
        boolean b = m.matches();
                
        if(!b){
          cont++;
          System.err.println("El nombre y los apellidos no son correctos");
              }
        
        return cont; 
            
    }
    
        
    


}


